name: Sync to HuggingFace
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://namberino:$HF_TOKEN@huggingface.co/spaces/namberino/mcq-generator main
