name: Scan docker image for security issues

on:
  push:
    branches: [ main ]

  pull_request:

  workflow_dispatch:

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build -t mcq-gen:ci .

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@0.32.0
        with:
          image-ref: mcq-gen:ci
          format: 'table'
          exit-code: '1'
