name: SAST

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install semgrep bandit

      - name: Run semgrep
        run: semgrep --config auto --output semgrep-results.txt || true

      - name: Run bandit
        run: bandit -r . -f json -o bandit-results.json || true

      - name: Upload SARIF/artifacts
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            semgrep-results.txt
            bandit-results.json
